## forward propogation

In [43]:
import pandas as pd
import numpy as np
df = pd.read_csv('../../AIML/AIML sem-1 notebooks/datasets/placement.csv',index_col=False)
df.head()

Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [44]:
def initialize_paramteres(layers_dimensions):
    np.random.seed(3)
    parameters = {}
    L = len(layers_dimensions)
    for l in range(1, L):
        parameters['W' + str(l)] = np.ones((layers_dimensions[l], layers_dimensions[l-1])) * 0.1    
        parameters['b' + str(l)] = np.zeros((layers_dimensions[l], 1))
    return parameters

In [45]:

def linear_forward(A_prev,W,b):
    Z = np.dot(W, A_prev) + b
    return Z

In [46]:

parameters = {}
layers_dimensions=[3,2,1]

In [47]:
L = len(layers_dimensions)
for l in range(1, L):
    print(np.ones((layers_dimensions[l], layers_dimensions[l-1])) * 0.1)
    parameters['W' + str(l)] = np.ones((layers_dimensions[l], layers_dimensions[l-1])) * 0.1
    print(np.zeros((layers_dimensions[l], 1)))
    parameters['b' + str(l)] = np.zeros((layers_dimensions[l], 1))

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
[[0.]
 [0.]]
[[0.1 0.1]]
[[0.]]


In [48]:
def relu(Z):
    return np.maximum(0,Z)

In [49]:
def sigmoid(Z):
    return 1/(1+np.exp(-Z))

In [50]:
def L_layer_forward(X,parameters):
    A=X
    caches = []
    L = len(parameters)//2
    for l in range(1,L):
        A_prev = A
        W = parameters['W' + str(l)]
        b = parameters['b' + str(l)]
        Z = linear_forward(A_prev,W,b)
        A = relu(Z)
        cache = (A_prev,W,b,Z)
        caches.append(cache)
    W_out = parameters['W' + str(L)]
    b_out = parameters['b' + str(L)]
    Z_out = linear_forward(A,W_out,b_out)
    AL = sigmoid(Z_out)
    return AL,caches

In [51]:
X = df.drop(columns=['placement']).values[0].reshape(3,1)
X.shape

(3, 1)

In [52]:
parameters = initialize_paramteres(layers_dimensions)

In [53]:
AL, caches = L_layer_forward(X, parameters)
print(AL)

[[0.9306037]]
